{
 "title": "Voting App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"vote-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"vote-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Running Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-pods\", pod=~\"vote-app-deployment.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}