apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: vote-app-container
        image: 722HDacr.azurecr.io/vote-app:latest
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_NAME
            value: "votes_db"
          - name: DB_USER
            value: "voteuser"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"