name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types: [completed]
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  BACKEND_IMAGE_NAME: vote-app
  FRONTEND_IMAGE_NAME: frontend-app
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  deploy:
    name: Deploy to AKS
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.IMAGE_TAG }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}

      - name: Deploy Monitoring Stack
        run: |
          kubectl apply -f k8s/prometheus-deployment.yml
          kubectl apply -f k8s/grafana-deployment.yml

      - name: Deploy Backend App
        run: |
          sed -i 's|image: .*|image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g' k8s/deployment.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/hpa.yml

      - name: Deploy Frontend App
        run: |
          # No IP injection needed anymore! Just update the image tag and apply.
          sed -i 's|image: .*|image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g' k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-service.yml