name: CD - Deploy to AKS

on:
  workflow_run:
    workflows: ["CI - Build and Push Images"]
    types: [completed]
    branches: [ "main" ]
  
  workflow_dispatch: {}

env:
  IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
  
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  BACKEND_IMAGE_NAME: vote-app
  FRONTEND_IMAGE_NAME: frontend-app
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  deploy:
    name: Provision and Deploy to AKS
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout specific commit from CI run
        uses: actions/checkout@v4
        with:
          ref: ${{ env.IMAGE_TAG }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy Monitoring Stack
        run: |
          echo "Applying Prometheus and Grafana manifests..."
          kubectl apply -f k8s/prometheus-deployment.yml
          kubectl apply -f k8s/grafana-deployment.yml

      - name: Deploy Backend App and Database
        run: |
          echo "1. Applying Kubernetes secret for the database..."
          kubectl apply -f k8s/secrets.yml

          echo "2. Applying PostgreSQL PVC, Deployment, and Service..."
          kubectl apply -f k8s/database-deployment.yml

          echo "3. Waiting for PostgreSQL to Stabilize..."
          kubectl rollout status deployment/postgres-deployment --timeout=300s
          
          echo "4. Deploying the backend application..."
          sed -i 's|image: .*|image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g' k8s/deployment.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/hpa.yml

      - name: Deploy Frontend App
        run: |
          echo "Deploying the frontend application..."
          sed -i 's|image: .*|image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g' k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-service.yml