name: CI - Build and Push Images

on:
  # This workflow runs on a push to the main branch
  push:
    branches: [ "main" ]
  
  workflow_dispatch: {}

env:
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  BACKEND_IMAGE_NAME: vote-app

jobs:
  build_and_push:
    name: Build, Scan, and Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      
      # (Future: Add pytest tests here)

      - name: Build Backend Docker image
        run: docker build ./app -t $REGISTRY/$BACKEND_IMAGE_NAME:${{ github.sha }}

      - name: Scan Backend Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '$REGISTRY/$BACKEND_IMAGE_NAME:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_NAME }} -p ${{ secrets.ACR_PASSWORD }}
      
      - name: Push Backend Image to ACR
        run: docker push $REGISTRY/$BACKEND_IMAGE_NAME:${{ github.sha }}